### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by NaiveInvestigator** [morrah/mpv-twitch-chat-irc#1]
```
Can not open external file D:/Program Files (x86)/mpv/portable_config/scripts/mpv-twitch-chat-irc/prod.txt.
[mpv_twitch_chat_irc] Traceback (most recent call last):
[mpv_twitch_chat_irc]   File "D:\Program Files (x86)\mpv\portable_config\scripts\mpv-twitch-chat-irc\ircdump.py", line 82, in <module>
[mpv_twitch_chat_irc]     main()
[mpv_twitch_chat_irc]   File "D:\Program Files (x86)\mpv\portable_config\scripts\mpv-twitch-chat-irc\ircdump.py", line 12, in main
[mpv_twitch_chat_irc]     connect_and_dump_loop(dumpfile, channel)
[mpv_twitch_chat_irc]   File "D:\Program Files (x86)\mpv\portable_config\scripts\mpv-twitch-chat-irc\ircdump.py", line 32, in connect_and_dump_loop
[mpv_twitch_chat_irc]     conn = ssl_socket(server, port)
[mpv_twitch_chat_irc]   File "D:\Program Files (x86)\mpv\portable_config\scripts\mpv-twitch-chat-irc\ircdump.py", line 19, in ssl_socket
[mpv_twitch_chat_irc]     ssock.connect((server, port))
[mpv_twitch_chat_irc]   File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1374, in connect
[mpv_twitch_chat_irc]     self._real_connect(addr, False)
[mpv_twitch_chat_irc]   File "C:\Users\Akid\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1352, in _real_connect
[mpv_twitch_chat_irc]     self._sslobj = self.context._wrap_socket(
[mpv_twitch_chat_irc] ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)
[mpv_twitch_chat_irc]
[mpv_twitch_chat_irc] stack traceback:
[mpv_twitch_chat_irc]   mp.defaults:510: in function 'call_event_handlers'
[mpv_twitch_chat_irc]   mp.defaults:552: in function 'dispatch_events'
[mpv_twitch_chat_irc]   mp.defaults:503: in function <mp.defaults:502>
[mpv_twitch_chat_irc]   [C]: at 0x7ff62b5e3340
[mpv_twitch_chat_irc]   [C]: at 0x7ff62b5e15c0
[mpv_twitch_chat_irc] Lua error: mp.defaults:637: attempt to call local 'cb' (a nil value)
```
After installing this script it spews out these errors. Is there any dependencies needed that i am missing? 

Edit: Link to stream: https://www.twitch.tv/prod

**Comment by morrah** [comment]
oh, my bad, read the docs wrong: thought [Purpose.CLIENT_AUTH](https://docs.python.org/3/library/ssl.html#ssl.create_default_context) is for a client side - and fun thing it worked fine up until python3.10

fixed, try it out please (haven't tested myself yet);
thank you and sorry for the delayed answer!

**Comment by NaiveInvestigator** [comment]
LMAOO I feel u fam. lol will try it out rn! TYSM!

Edit: tested it rn, works like a charm! TYSM again!
